// Code generated by MockGen. DO NOT EDIT.
// Source: auth_interactor_inputport.go
//
// Generated by this command:
//
//	mockgen -source=auth_interactor_inputport.go -destination=mock/auth_interactor_inputport.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockAuthInteractorInputPort is a mock of AuthInteractorInputPort interface.
type MockAuthInteractorInputPort struct {
	ctrl     *gomock.Controller
	recorder *MockAuthInteractorInputPortMockRecorder
	isgomock struct{}
}

// MockAuthInteractorInputPortMockRecorder is the mock recorder for MockAuthInteractorInputPort.
type MockAuthInteractorInputPortMockRecorder struct {
	mock *MockAuthInteractorInputPort
}

// NewMockAuthInteractorInputPort creates a new mock instance.
func NewMockAuthInteractorInputPort(ctrl *gomock.Controller) *MockAuthInteractorInputPort {
	mock := &MockAuthInteractorInputPort{ctrl: ctrl}
	mock.recorder = &MockAuthInteractorInputPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthInteractorInputPort) EXPECT() *MockAuthInteractorInputPortMockRecorder {
	return m.recorder
}

// Callback mocks base method.
func (m *MockAuthInteractorInputPort) Callback(ctx context.Context, code string) (string, time.Time, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Callback", ctx, code)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(time.Time)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Callback indicates an expected call of Callback.
func (mr *MockAuthInteractorInputPortMockRecorder) Callback(ctx, code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Callback", reflect.TypeOf((*MockAuthInteractorInputPort)(nil).Callback), ctx, code)
}

// DeleteUserSession mocks base method.
func (m *MockAuthInteractorInputPort) DeleteUserSession(ctx context.Context, userId, session_id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUserSession", ctx, userId, session_id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteUserSession indicates an expected call of DeleteUserSession.
func (mr *MockAuthInteractorInputPortMockRecorder) DeleteUserSession(ctx, userId, session_id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUserSession", reflect.TypeOf((*MockAuthInteractorInputPort)(nil).DeleteUserSession), ctx, userId, session_id)
}

// SignIn mocks base method.
func (m *MockAuthInteractorInputPort) SignIn(ctx context.Context) (string, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SignIn", ctx)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// SignIn indicates an expected call of SignIn.
func (mr *MockAuthInteractorInputPortMockRecorder) SignIn(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SignIn", reflect.TypeOf((*MockAuthInteractorInputPort)(nil).SignIn), ctx)
}
