// Code generated by MockGen. DO NOT EDIT.
// Source: problems_interactor_inputport.go
//
// Generated by this command:
//
//	mockgen -source=problems_interactor_inputport.go -destination=mock/problems_interactor_inputport.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	entities "backend/internal/domain/entities"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockProblemsInteractorInputPort is a mock of ProblemsInteractorInputPort interface.
type MockProblemsInteractorInputPort struct {
	ctrl     *gomock.Controller
	recorder *MockProblemsInteractorInputPortMockRecorder
	isgomock struct{}
}

// MockProblemsInteractorInputPortMockRecorder is the mock recorder for MockProblemsInteractorInputPort.
type MockProblemsInteractorInputPortMockRecorder struct {
	mock *MockProblemsInteractorInputPort
}

// NewMockProblemsInteractorInputPort creates a new mock instance.
func NewMockProblemsInteractorInputPort(ctrl *gomock.Controller) *MockProblemsInteractorInputPort {
	mock := &MockProblemsInteractorInputPort{ctrl: ctrl}
	mock.recorder = &MockProblemsInteractorInputPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProblemsInteractorInputPort) EXPECT() *MockProblemsInteractorInputPortMockRecorder {
	return m.recorder
}

// GetProblems mocks base method.
func (m *MockProblemsInteractorInputPort) GetProblems(ctx context.Context, userId string, status entities.ProblemStatus) ([]entities.Problems, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProblems", ctx, userId, status)
	ret0, _ := ret[0].([]entities.Problems)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProblems indicates an expected call of GetProblems.
func (mr *MockProblemsInteractorInputPortMockRecorder) GetProblems(ctx, userId, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProblems", reflect.TypeOf((*MockProblemsInteractorInputPort)(nil).GetProblems), ctx, userId, status)
}
