// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/interactor/inputport/problems_interactor_inputport.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/interactor/inputport/problems_interactor_inputport.go -destination=internal/domain/interactor/inputport/mock/problems_interactor_inputport.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	entities "backend/internal/domain/entities"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockProblemsInteractorInputPort is a mock of ProblemsInteractorInputPort interface.
type MockProblemsInteractorInputPort struct {
	ctrl     *gomock.Controller
	recorder *MockProblemsInteractorInputPortMockRecorder
	isgomock struct{}
}

// MockProblemsInteractorInputPortMockRecorder is the mock recorder for MockProblemsInteractorInputPort.
type MockProblemsInteractorInputPortMockRecorder struct {
	mock *MockProblemsInteractorInputPort
}

// NewMockProblemsInteractorInputPort creates a new mock instance.
func NewMockProblemsInteractorInputPort(ctrl *gomock.Controller) *MockProblemsInteractorInputPort {
	mock := &MockProblemsInteractorInputPort{ctrl: ctrl}
	mock.recorder = &MockProblemsInteractorInputPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProblemsInteractorInputPort) EXPECT() *MockProblemsInteractorInputPortMockRecorder {
	return m.recorder
}

// GetAIHelp mocks base method.
func (m *MockProblemsInteractorInputPort) GetAIHelp(ctx context.Context, userId, problemId string) (entities.AIHelp, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAIHelp", ctx, userId, problemId)
	ret0, _ := ret[0].(entities.AIHelp)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAIHelp indicates an expected call of GetAIHelp.
func (mr *MockProblemsInteractorInputPortMockRecorder) GetAIHelp(ctx, userId, problemId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAIHelp", reflect.TypeOf((*MockProblemsInteractorInputPort)(nil).GetAIHelp), ctx, userId, problemId)
}

// GetProblemDetails mocks base method.
func (m *MockProblemsInteractorInputPort) GetProblemDetails(ctx context.Context, userId, problemId string) (entities.Problems, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProblemDetails", ctx, userId, problemId)
	ret0, _ := ret[0].(entities.Problems)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProblemDetails indicates an expected call of GetProblemDetails.
func (mr *MockProblemsInteractorInputPortMockRecorder) GetProblemDetails(ctx, userId, problemId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProblemDetails", reflect.TypeOf((*MockProblemsInteractorInputPort)(nil).GetProblemDetails), ctx, userId, problemId)
}

// GetProblems mocks base method.
func (m *MockProblemsInteractorInputPort) GetProblems(ctx context.Context, userId string, status entities.ProblemStatus, difficulty entities.ProblemDifficulty) ([]entities.Problems, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProblems", ctx, userId, status, difficulty)
	ret0, _ := ret[0].([]entities.Problems)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProblems indicates an expected call of GetProblems.
func (mr *MockProblemsInteractorInputPortMockRecorder) GetProblems(ctx, userId, status, difficulty any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProblems", reflect.TypeOf((*MockProblemsInteractorInputPort)(nil).GetProblems), ctx, userId, status, difficulty)
}

// GetTodaysProblem mocks base method.
func (m *MockProblemsInteractorInputPort) GetTodaysProblem(ctx context.Context, userId string) (entities.Problems, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTodaysProblem", ctx, userId)
	ret0, _ := ret[0].(entities.Problems)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTodaysProblem indicates an expected call of GetTodaysProblem.
func (mr *MockProblemsInteractorInputPortMockRecorder) GetTodaysProblem(ctx, userId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTodaysProblem", reflect.TypeOf((*MockProblemsInteractorInputPort)(nil).GetTodaysProblem), ctx, userId)
}
