// Code generated by MockGen. DO NOT EDIT.
// Source: settings_interactor_inputport.go
//
// Generated by this command:
//
//	mockgen -source=settings_interactor_inputport.go -destination=mock/settings_interactor_inputport.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	entities "backend/internal/domain/entities"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockSettingsInteractorInputPort is a mock of SettingsInteractorInputPort interface.
type MockSettingsInteractorInputPort struct {
	ctrl     *gomock.Controller
	recorder *MockSettingsInteractorInputPortMockRecorder
	isgomock struct{}
}

// MockSettingsInteractorInputPortMockRecorder is the mock recorder for MockSettingsInteractorInputPort.
type MockSettingsInteractorInputPortMockRecorder struct {
	mock *MockSettingsInteractorInputPort
}

// NewMockSettingsInteractorInputPort creates a new mock instance.
func NewMockSettingsInteractorInputPort(ctrl *gomock.Controller) *MockSettingsInteractorInputPort {
	mock := &MockSettingsInteractorInputPort{ctrl: ctrl}
	mock.recorder = &MockSettingsInteractorInputPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSettingsInteractorInputPort) EXPECT() *MockSettingsInteractorInputPortMockRecorder {
	return m.recorder
}

// GetUserSetting mocks base method.
func (m *MockSettingsInteractorInputPort) GetUserSetting(ctx context.Context, userId string) (entities.Settings, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserSetting", ctx, userId)
	ret0, _ := ret[0].(entities.Settings)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserSetting indicates an expected call of GetUserSetting.
func (mr *MockSettingsInteractorInputPortMockRecorder) GetUserSetting(ctx, userId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserSetting", reflect.TypeOf((*MockSettingsInteractorInputPort)(nil).GetUserSetting), ctx, userId)
}
