// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/interactor/inputport/submitted_solutions_interactor_inputport.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/interactor/inputport/submitted_solutions_interactor_inputport.go -destination=internal/domain/interactor/inputport/mock/submitted_solutions_interactor_inputport.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	entities "backend/internal/domain/entities"
	response "backend/internal/response"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockSubmittedSolutionsInteractorInputPort is a mock of SubmittedSolutionsInteractorInputPort interface.
type MockSubmittedSolutionsInteractorInputPort struct {
	ctrl     *gomock.Controller
	recorder *MockSubmittedSolutionsInteractorInputPortMockRecorder
	isgomock struct{}
}

// MockSubmittedSolutionsInteractorInputPortMockRecorder is the mock recorder for MockSubmittedSolutionsInteractorInputPort.
type MockSubmittedSolutionsInteractorInputPortMockRecorder struct {
	mock *MockSubmittedSolutionsInteractorInputPort
}

// NewMockSubmittedSolutionsInteractorInputPort creates a new mock instance.
func NewMockSubmittedSolutionsInteractorInputPort(ctrl *gomock.Controller) *MockSubmittedSolutionsInteractorInputPort {
	mock := &MockSubmittedSolutionsInteractorInputPort{ctrl: ctrl}
	mock.recorder = &MockSubmittedSolutionsInteractorInputPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSubmittedSolutionsInteractorInputPort) EXPECT() *MockSubmittedSolutionsInteractorInputPortMockRecorder {
	return m.recorder
}

// GetDatesForHeatMap mocks base method.
func (m *MockSubmittedSolutionsInteractorInputPort) GetDatesForHeatMap(c context.Context, userId string) ([]response.HeatMapDates, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDatesForHeatMap", c, userId)
	ret0, _ := ret[0].([]response.HeatMapDates)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDatesForHeatMap indicates an expected call of GetDatesForHeatMap.
func (mr *MockSubmittedSolutionsInteractorInputPortMockRecorder) GetDatesForHeatMap(c, userId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDatesForHeatMap", reflect.TypeOf((*MockSubmittedSolutionsInteractorInputPort)(nil).GetDatesForHeatMap), c, userId)
}

// GetSubmittedSolutions mocks base method.
func (m *MockSubmittedSolutionsInteractorInputPort) GetSubmittedSolutions(ctx context.Context, userId, problemId string) ([]entities.SubmittedSolutions, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSubmittedSolutions", ctx, userId, problemId)
	ret0, _ := ret[0].([]entities.SubmittedSolutions)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSubmittedSolutions indicates an expected call of GetSubmittedSolutions.
func (mr *MockSubmittedSolutionsInteractorInputPortMockRecorder) GetSubmittedSolutions(ctx, userId, problemId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSubmittedSolutions", reflect.TypeOf((*MockSubmittedSolutionsInteractorInputPort)(nil).GetSubmittedSolutions), ctx, userId, problemId)
}

// RunSubmission mocks base method.
func (m *MockSubmittedSolutionsInteractorInputPort) RunSubmission(ctx context.Context, request entities.SubmittedSolutionForExecution) (response.ExecuteSubmissionResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RunSubmission", ctx, request)
	ret0, _ := ret[0].(response.ExecuteSubmissionResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RunSubmission indicates an expected call of RunSubmission.
func (mr *MockSubmittedSolutionsInteractorInputPortMockRecorder) RunSubmission(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunSubmission", reflect.TypeOf((*MockSubmittedSolutionsInteractorInputPort)(nil).RunSubmission), ctx, request)
}

// SubmitSolution mocks base method.
func (m *MockSubmittedSolutionsInteractorInputPort) SubmitSolution(ctx context.Context, userId, problemId string, submittedSolutionBody entities.SubmittedSolutionsBody) (entities.SubmittedSolutions, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubmitSolution", ctx, userId, problemId, submittedSolutionBody)
	ret0, _ := ret[0].(entities.SubmittedSolutions)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SubmitSolution indicates an expected call of SubmitSolution.
func (mr *MockSubmittedSolutionsInteractorInputPortMockRecorder) SubmitSolution(ctx, userId, problemId, submittedSolutionBody any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubmitSolution", reflect.TypeOf((*MockSubmittedSolutionsInteractorInputPort)(nil).SubmitSolution), ctx, userId, problemId, submittedSolutionBody)
}
