// Code generated by MockGen. DO NOT EDIT.
// Source: submitted_solutions_interactor_inputport.go
//
// Generated by this command:
//
//	mockgen -source=submitted_solutions_interactor_inputport.go -destination=mock/submitted_solutions_interactor_inputport.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	entities "backend/internal/domain/entities"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockSubmittedSolutionsInteractorInputPort is a mock of SubmittedSolutionsInteractorInputPort interface.
type MockSubmittedSolutionsInteractorInputPort struct {
	ctrl     *gomock.Controller
	recorder *MockSubmittedSolutionsInteractorInputPortMockRecorder
	isgomock struct{}
}

// MockSubmittedSolutionsInteractorInputPortMockRecorder is the mock recorder for MockSubmittedSolutionsInteractorInputPort.
type MockSubmittedSolutionsInteractorInputPortMockRecorder struct {
	mock *MockSubmittedSolutionsInteractorInputPort
}

// NewMockSubmittedSolutionsInteractorInputPort creates a new mock instance.
func NewMockSubmittedSolutionsInteractorInputPort(ctrl *gomock.Controller) *MockSubmittedSolutionsInteractorInputPort {
	mock := &MockSubmittedSolutionsInteractorInputPort{ctrl: ctrl}
	mock.recorder = &MockSubmittedSolutionsInteractorInputPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSubmittedSolutionsInteractorInputPort) EXPECT() *MockSubmittedSolutionsInteractorInputPortMockRecorder {
	return m.recorder
}

// GetSubmittedSolutions mocks base method.
func (m *MockSubmittedSolutionsInteractorInputPort) GetSubmittedSolutions(ctx context.Context, userId, problemId string) ([]entities.SubmittedSolutions, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSubmittedSolutions", ctx, userId, problemId)
	ret0, _ := ret[0].([]entities.SubmittedSolutions)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSubmittedSolutions indicates an expected call of GetSubmittedSolutions.
func (mr *MockSubmittedSolutionsInteractorInputPortMockRecorder) GetSubmittedSolutions(ctx, userId, problemId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSubmittedSolutions", reflect.TypeOf((*MockSubmittedSolutionsInteractorInputPort)(nil).GetSubmittedSolutions), ctx, userId, problemId)
}
