// Code generated by MockGen. DO NOT EDIT.
// Source: ingest_runner_inputport.go
//
// Generated by this command:
//
//	mockgen -source=ingest_runner_inputport.go -destination=mock/ingest_runner_inputport.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockIngestRunnerInputPort is a mock of IngestRunnerInputPort interface.
type MockIngestRunnerInputPort struct {
	ctrl     *gomock.Controller
	recorder *MockIngestRunnerInputPortMockRecorder
	isgomock struct{}
}

// MockIngestRunnerInputPortMockRecorder is the mock recorder for MockIngestRunnerInputPort.
type MockIngestRunnerInputPortMockRecorder struct {
	mock *MockIngestRunnerInputPort
}

// NewMockIngestRunnerInputPort creates a new mock instance.
func NewMockIngestRunnerInputPort(ctrl *gomock.Controller) *MockIngestRunnerInputPort {
	mock := &MockIngestRunnerInputPort{ctrl: ctrl}
	mock.recorder = &MockIngestRunnerInputPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIngestRunnerInputPort) EXPECT() *MockIngestRunnerInputPortMockRecorder {
	return m.recorder
}

// Ingest mocks base method.
func (m *MockIngestRunnerInputPort) Ingest(ctx context.Context, userIds []string, retried bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ingest", ctx, userIds, retried)
	ret0, _ := ret[0].(error)
	return ret0
}

// Ingest indicates an expected call of Ingest.
func (mr *MockIngestRunnerInputPortMockRecorder) Ingest(ctx, userIds, retried any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ingest", reflect.TypeOf((*MockIngestRunnerInputPort)(nil).Ingest), ctx, userIds, retried)
}
