// Code generated by MockGen. DO NOT EDIT.
// Source: ingest_repository_inputport.go
//
// Generated by this command:
//
//	mockgen -source=ingest_repository_inputport.go -destination=mock/ingest_repository_inputport.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	entities "backend/internal/domain/entities"
	context "context"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockIngestRepositoryInputPort is a mock of IngestRepositoryInputPort interface.
type MockIngestRepositoryInputPort struct {
	ctrl     *gomock.Controller
	recorder *MockIngestRepositoryInputPortMockRecorder
	isgomock struct{}
}

// MockIngestRepositoryInputPortMockRecorder is the mock recorder for MockIngestRepositoryInputPort.
type MockIngestRepositoryInputPortMockRecorder struct {
	mock *MockIngestRepositoryInputPort
}

// NewMockIngestRepositoryInputPort creates a new mock instance.
func NewMockIngestRepositoryInputPort(ctrl *gomock.Controller) *MockIngestRepositoryInputPort {
	mock := &MockIngestRepositoryInputPort{ctrl: ctrl}
	mock.recorder = &MockIngestRepositoryInputPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIngestRepositoryInputPort) EXPECT() *MockIngestRepositoryInputPortMockRecorder {
	return m.recorder
}

// CreateIngestWithErr mocks base method.
func (m *MockIngestRepositoryInputPort) CreateIngestWithErr(ctx context.Context, ingest entities.IngestRuns) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateIngestWithErr", ctx, ingest)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateIngestWithErr indicates an expected call of CreateIngestWithErr.
func (mr *MockIngestRepositoryInputPortMockRecorder) CreateIngestWithErr(ctx, ingest any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateIngestWithErr", reflect.TypeOf((*MockIngestRepositoryInputPort)(nil).CreateIngestWithErr), ctx, ingest)
}

// GetIngestByUserId mocks base method.
func (m *MockIngestRepositoryInputPort) GetIngestByUserId(ctx context.Context, userId string, ingestDate time.Time, retried bool) ([]entities.IngestRuns, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIngestByUserId", ctx, userId, ingestDate, retried)
	ret0, _ := ret[0].([]entities.IngestRuns)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetIngestByUserId indicates an expected call of GetIngestByUserId.
func (mr *MockIngestRepositoryInputPortMockRecorder) GetIngestByUserId(ctx, userId, ingestDate, retried any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIngestByUserId", reflect.TypeOf((*MockIngestRepositoryInputPort)(nil).GetIngestByUserId), ctx, userId, ingestDate, retried)
}
