// Code generated by MockGen. DO NOT EDIT.
// Source: oauth_repository_inputport.go
//
// Generated by this command:
//
//	mockgen -source=oauth_repository_inputport.go -destination=mock/oauth_repository_inputport.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	entities "backend/internal/domain/entities"
	context "context"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockOauthRepositoryInputPort is a mock of OauthRepositoryInputPort interface.
type MockOauthRepositoryInputPort struct {
	ctrl     *gomock.Controller
	recorder *MockOauthRepositoryInputPortMockRecorder
	isgomock struct{}
}

// MockOauthRepositoryInputPortMockRecorder is the mock recorder for MockOauthRepositoryInputPort.
type MockOauthRepositoryInputPortMockRecorder struct {
	mock *MockOauthRepositoryInputPort
}

// NewMockOauthRepositoryInputPort creates a new mock instance.
func NewMockOauthRepositoryInputPort(ctrl *gomock.Controller) *MockOauthRepositoryInputPort {
	mock := &MockOauthRepositoryInputPort{ctrl: ctrl}
	mock.recorder = &MockOauthRepositoryInputPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOauthRepositoryInputPort) EXPECT() *MockOauthRepositoryInputPortMockRecorder {
	return m.recorder
}

// CreateOauthCredentials mocks base method.
func (m *MockOauthRepositoryInputPort) CreateOauthCredentials(ctx context.Context, oauthCreds *entities.OauthCredentials) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOauthCredentials", ctx, oauthCreds)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateOauthCredentials indicates an expected call of CreateOauthCredentials.
func (mr *MockOauthRepositoryInputPortMockRecorder) CreateOauthCredentials(ctx, oauthCreds any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOauthCredentials", reflect.TypeOf((*MockOauthRepositoryInputPort)(nil).CreateOauthCredentials), ctx, oauthCreds)
}

// FindUserBySub mocks base method.
func (m *MockOauthRepositoryInputPort) FindUserBySub(ctx context.Context, sub string) (*entities.OauthCredentials, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindUserBySub", ctx, sub)
	ret0, _ := ret[0].(*entities.OauthCredentials)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindUserBySub indicates an expected call of FindUserBySub.
func (mr *MockOauthRepositoryInputPortMockRecorder) FindUserBySub(ctx, sub any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindUserBySub", reflect.TypeOf((*MockOauthRepositoryInputPort)(nil).FindUserBySub), ctx, sub)
}

// UpdateOauthInformationWithSub mocks base method.
func (m *MockOauthRepositoryInputPort) UpdateOauthInformationWithSub(ctx context.Context, sub, refreshToken string, expiryAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateOauthInformationWithSub", ctx, sub, refreshToken, expiryAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateOauthInformationWithSub indicates an expected call of UpdateOauthInformationWithSub.
func (mr *MockOauthRepositoryInputPortMockRecorder) UpdateOauthInformationWithSub(ctx, sub, refreshToken, expiryAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateOauthInformationWithSub", reflect.TypeOf((*MockOauthRepositoryInputPort)(nil).UpdateOauthInformationWithSub), ctx, sub, refreshToken, expiryAt)
}
