// Code generated by MockGen. DO NOT EDIT.
// Source: piston_api_repository_inputport.go
//
// Generated by this command:
//
//	mockgen -source=piston_api_repository_inputport.go -destination=mock/piston_api_repository_inputport.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	entities "backend/internal/domain/entities"
	response "backend/internal/response"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockPistonApiRepositoryInputport is a mock of PistonApiRepositoryInputport interface.
type MockPistonApiRepositoryInputport struct {
	ctrl     *gomock.Controller
	recorder *MockPistonApiRepositoryInputportMockRecorder
	isgomock struct{}
}

// MockPistonApiRepositoryInputportMockRecorder is the mock recorder for MockPistonApiRepositoryInputport.
type MockPistonApiRepositoryInputportMockRecorder struct {
	mock *MockPistonApiRepositoryInputport
}

// NewMockPistonApiRepositoryInputport creates a new mock instance.
func NewMockPistonApiRepositoryInputport(ctrl *gomock.Controller) *MockPistonApiRepositoryInputport {
	mock := &MockPistonApiRepositoryInputport{ctrl: ctrl}
	mock.recorder = &MockPistonApiRepositoryInputportMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPistonApiRepositoryInputport) EXPECT() *MockPistonApiRepositoryInputportMockRecorder {
	return m.recorder
}

// RunSubmission mocks base method.
func (m *MockPistonApiRepositoryInputport) RunSubmission(ctx context.Context, request entities.SubmittedSolutionRequest) (response.ExecuteSubmissionResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RunSubmission", ctx, request)
	ret0, _ := ret[0].(response.ExecuteSubmissionResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RunSubmission indicates an expected call of RunSubmission.
func (mr *MockPistonApiRepositoryInputportMockRecorder) RunSubmission(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunSubmission", reflect.TypeOf((*MockPistonApiRepositoryInputport)(nil).RunSubmission), ctx, request)
}
