// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/repository/inputport/problems_repository_inputport.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/repository/inputport/problems_repository_inputport.go -destination=internal/domain/repository/inputport/mock/problems_repository_inputport.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	entities "backend/internal/domain/entities"
	context "context"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockProblemsRepositoryInputPort is a mock of ProblemsRepositoryInputPort interface.
type MockProblemsRepositoryInputPort struct {
	ctrl     *gomock.Controller
	recorder *MockProblemsRepositoryInputPortMockRecorder
	isgomock struct{}
}

// MockProblemsRepositoryInputPortMockRecorder is the mock recorder for MockProblemsRepositoryInputPort.
type MockProblemsRepositoryInputPortMockRecorder struct {
	mock *MockProblemsRepositoryInputPort
}

// NewMockProblemsRepositoryInputPort creates a new mock instance.
func NewMockProblemsRepositoryInputPort(ctrl *gomock.Controller) *MockProblemsRepositoryInputPort {
	mock := &MockProblemsRepositoryInputPort{ctrl: ctrl}
	mock.recorder = &MockProblemsRepositoryInputPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProblemsRepositoryInputPort) EXPECT() *MockProblemsRepositoryInputPortMockRecorder {
	return m.recorder
}

// CreateProblem mocks base method.
func (m *MockProblemsRepositoryInputPort) CreateProblem(ctx context.Context, problem *entities.Problems) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateProblem", ctx, problem)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateProblem indicates an expected call of CreateProblem.
func (mr *MockProblemsRepositoryInputPortMockRecorder) CreateProblem(ctx, problem any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateProblem", reflect.TypeOf((*MockProblemsRepositoryInputPort)(nil).CreateProblem), ctx, problem)
}

// GetProblemDetails mocks base method.
func (m *MockProblemsRepositoryInputPort) GetProblemDetails(ctx context.Context, userId, problemId string) (entities.Problems, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProblemDetails", ctx, userId, problemId)
	ret0, _ := ret[0].(entities.Problems)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProblemDetails indicates an expected call of GetProblemDetails.
func (mr *MockProblemsRepositoryInputPortMockRecorder) GetProblemDetails(ctx, userId, problemId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProblemDetails", reflect.TypeOf((*MockProblemsRepositoryInputPort)(nil).GetProblemDetails), ctx, userId, problemId)
}

// GetProblems mocks base method.
func (m *MockProblemsRepositoryInputPort) GetProblems(ctx context.Context, userId, status, difficulty string) ([]entities.Problems, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProblems", ctx, userId, status, difficulty)
	ret0, _ := ret[0].([]entities.Problems)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProblems indicates an expected call of GetProblems.
func (mr *MockProblemsRepositoryInputPortMockRecorder) GetProblems(ctx, userId, status, difficulty any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProblems", reflect.TypeOf((*MockProblemsRepositoryInputPort)(nil).GetProblems), ctx, userId, status, difficulty)
}

// GetProblemsCount mocks base method.
func (m *MockProblemsRepositoryInputPort) GetProblemsCount(ctx context.Context, userId string) (entities.ProblemStateCount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProblemsCount", ctx, userId)
	ret0, _ := ret[0].(entities.ProblemStateCount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProblemsCount indicates an expected call of GetProblemsCount.
func (mr *MockProblemsRepositoryInputPortMockRecorder) GetProblemsCount(ctx, userId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProblemsCount", reflect.TypeOf((*MockProblemsRepositoryInputPort)(nil).GetProblemsCount), ctx, userId)
}

// GetTodaysproblem mocks base method.
func (m *MockProblemsRepositoryInputPort) GetTodaysproblem(ctx context.Context, userId string, todaysDate time.Time) (entities.Problems, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTodaysproblem", ctx, userId, todaysDate)
	ret0, _ := ret[0].(entities.Problems)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTodaysproblem indicates an expected call of GetTodaysproblem.
func (mr *MockProblemsRepositoryInputPortMockRecorder) GetTodaysproblem(ctx, userId, todaysDate any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTodaysproblem", reflect.TypeOf((*MockProblemsRepositoryInputPort)(nil).GetTodaysproblem), ctx, userId, todaysDate)
}

// UpdateProblemWithAIHelp mocks base method.
func (m *MockProblemsRepositoryInputPort) UpdateProblemWithAIHelp(ctx context.Context, userId, problemId, aiHelp string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateProblemWithAIHelp", ctx, userId, problemId, aiHelp)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateProblemWithAIHelp indicates an expected call of UpdateProblemWithAIHelp.
func (mr *MockProblemsRepositoryInputPortMockRecorder) UpdateProblemWithAIHelp(ctx, userId, problemId, aiHelp any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateProblemWithAIHelp", reflect.TypeOf((*MockProblemsRepositoryInputPort)(nil).UpdateProblemWithAIHelp), ctx, userId, problemId, aiHelp)
}
