// Code generated by MockGen. DO NOT EDIT.
// Source: sessions_repository_inputport.go
//
// Generated by this command:
//
//	mockgen -source=sessions_repository_inputport.go -destination=mock/sessions_repository_inputport.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	entities "backend/internal/domain/entities"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockSessionsRepositoryInputPort is a mock of SessionsRepositoryInputPort interface.
type MockSessionsRepositoryInputPort struct {
	ctrl     *gomock.Controller
	recorder *MockSessionsRepositoryInputPortMockRecorder
	isgomock struct{}
}

// MockSessionsRepositoryInputPortMockRecorder is the mock recorder for MockSessionsRepositoryInputPort.
type MockSessionsRepositoryInputPortMockRecorder struct {
	mock *MockSessionsRepositoryInputPort
}

// NewMockSessionsRepositoryInputPort creates a new mock instance.
func NewMockSessionsRepositoryInputPort(ctrl *gomock.Controller) *MockSessionsRepositoryInputPort {
	mock := &MockSessionsRepositoryInputPort{ctrl: ctrl}
	mock.recorder = &MockSessionsRepositoryInputPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSessionsRepositoryInputPort) EXPECT() *MockSessionsRepositoryInputPortMockRecorder {
	return m.recorder
}

// CreateSession mocks base method.
func (m *MockSessionsRepositoryInputPort) CreateSession(ctx context.Context, session *entities.Sessions) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSession", ctx, session)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateSession indicates an expected call of CreateSession.
func (mr *MockSessionsRepositoryInputPortMockRecorder) CreateSession(ctx, session any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSession", reflect.TypeOf((*MockSessionsRepositoryInputPort)(nil).CreateSession), ctx, session)
}

// GetSessionById mocks base method.
func (m *MockSessionsRepositoryInputPort) GetSessionById(ctx context.Context, sessionId string) (*entities.Sessions, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSessionById", ctx, sessionId)
	ret0, _ := ret[0].(*entities.Sessions)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSessionById indicates an expected call of GetSessionById.
func (mr *MockSessionsRepositoryInputPortMockRecorder) GetSessionById(ctx, sessionId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSessionById", reflect.TypeOf((*MockSessionsRepositoryInputPort)(nil).GetSessionById), ctx, sessionId)
}
