// Code generated by MockGen. DO NOT EDIT.
// Source: settings_repository_inputport.go
//
// Generated by this command:
//
//	mockgen -source=settings_repository_inputport.go -destination=mock/settings_repository_inputport.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	entities "backend/internal/domain/entities"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockSettingsRepositoryInputPort is a mock of SettingsRepositoryInputPort interface.
type MockSettingsRepositoryInputPort struct {
	ctrl     *gomock.Controller
	recorder *MockSettingsRepositoryInputPortMockRecorder
	isgomock struct{}
}

// MockSettingsRepositoryInputPortMockRecorder is the mock recorder for MockSettingsRepositoryInputPort.
type MockSettingsRepositoryInputPortMockRecorder struct {
	mock *MockSettingsRepositoryInputPort
}

// NewMockSettingsRepositoryInputPort creates a new mock instance.
func NewMockSettingsRepositoryInputPort(ctrl *gomock.Controller) *MockSettingsRepositoryInputPort {
	mock := &MockSettingsRepositoryInputPort{ctrl: ctrl}
	mock.recorder = &MockSettingsRepositoryInputPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSettingsRepositoryInputPort) EXPECT() *MockSettingsRepositoryInputPortMockRecorder {
	return m.recorder
}

// CreateSetting mocks base method.
func (m *MockSettingsRepositoryInputPort) CreateSetting(ctx context.Context, setting *entities.Settings) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSetting", ctx, setting)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateSetting indicates an expected call of CreateSetting.
func (mr *MockSettingsRepositoryInputPortMockRecorder) CreateSetting(ctx, setting any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSetting", reflect.TypeOf((*MockSettingsRepositoryInputPort)(nil).CreateSetting), ctx, setting)
}

// GetUserSetting mocks base method.
func (m *MockSettingsRepositoryInputPort) GetUserSetting(ctx context.Context, userId string) (entities.Settings, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserSetting", ctx, userId)
	ret0, _ := ret[0].(entities.Settings)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserSetting indicates an expected call of GetUserSetting.
func (mr *MockSettingsRepositoryInputPortMockRecorder) GetUserSetting(ctx, userId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserSetting", reflect.TypeOf((*MockSettingsRepositoryInputPort)(nil).GetUserSetting), ctx, userId)
}
