// Code generated by MockGen. DO NOT EDIT.
// Source: submitted_solutions_repository_inputport.go
//
// Generated by this command:
//
//	mockgen -source=submitted_solutions_repository_inputport.go -destination=mock/submitted_solutions_repository_inputport.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	entities "backend/internal/domain/entities"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockSubmittedSolutionsRepositoryInputPort is a mock of SubmittedSolutionsRepositoryInputPort interface.
type MockSubmittedSolutionsRepositoryInputPort struct {
	ctrl     *gomock.Controller
	recorder *MockSubmittedSolutionsRepositoryInputPortMockRecorder
	isgomock struct{}
}

// MockSubmittedSolutionsRepositoryInputPortMockRecorder is the mock recorder for MockSubmittedSolutionsRepositoryInputPort.
type MockSubmittedSolutionsRepositoryInputPortMockRecorder struct {
	mock *MockSubmittedSolutionsRepositoryInputPort
}

// NewMockSubmittedSolutionsRepositoryInputPort creates a new mock instance.
func NewMockSubmittedSolutionsRepositoryInputPort(ctrl *gomock.Controller) *MockSubmittedSolutionsRepositoryInputPort {
	mock := &MockSubmittedSolutionsRepositoryInputPort{ctrl: ctrl}
	mock.recorder = &MockSubmittedSolutionsRepositoryInputPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSubmittedSolutionsRepositoryInputPort) EXPECT() *MockSubmittedSolutionsRepositoryInputPortMockRecorder {
	return m.recorder
}

// GetSubmittedSolutions mocks base method.
func (m *MockSubmittedSolutionsRepositoryInputPort) GetSubmittedSolutions(ctx context.Context, userId, problemId string) ([]entities.SubmittedSolutions, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSubmittedSolutions", ctx, userId, problemId)
	ret0, _ := ret[0].([]entities.SubmittedSolutions)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSubmittedSolutions indicates an expected call of GetSubmittedSolutions.
func (mr *MockSubmittedSolutionsRepositoryInputPortMockRecorder) GetSubmittedSolutions(ctx, userId, problemId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSubmittedSolutions", reflect.TypeOf((*MockSubmittedSolutionsRepositoryInputPort)(nil).GetSubmittedSolutions), ctx, userId, problemId)
}

// SubmitSolution mocks base method.
func (m *MockSubmittedSolutionsRepositoryInputPort) SubmitSolution(ctx context.Context, submittedSolution entities.SubmittedSolutions) (entities.SubmittedSolutions, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubmitSolution", ctx, submittedSolution)
	ret0, _ := ret[0].(entities.SubmittedSolutions)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SubmitSolution indicates an expected call of SubmitSolution.
func (mr *MockSubmittedSolutionsRepositoryInputPortMockRecorder) SubmitSolution(ctx, submittedSolution any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubmitSolution", reflect.TypeOf((*MockSubmittedSolutionsRepositoryInputPort)(nil).SubmitSolution), ctx, submittedSolution)
}
