// Code generated by MockGen. DO NOT EDIT.
// Source: users_repository_inputport.go
//
// Generated by this command:
//
//	mockgen -source=users_repository_inputport.go -destination=mock/users_repository_inputport.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	entities "backend/internal/domain/entities"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockUsersRepositoryInputPort is a mock of UsersRepositoryInputPort interface.
type MockUsersRepositoryInputPort struct {
	ctrl     *gomock.Controller
	recorder *MockUsersRepositoryInputPortMockRecorder
	isgomock struct{}
}

// MockUsersRepositoryInputPortMockRecorder is the mock recorder for MockUsersRepositoryInputPort.
type MockUsersRepositoryInputPortMockRecorder struct {
	mock *MockUsersRepositoryInputPort
}

// NewMockUsersRepositoryInputPort creates a new mock instance.
func NewMockUsersRepositoryInputPort(ctrl *gomock.Controller) *MockUsersRepositoryInputPort {
	mock := &MockUsersRepositoryInputPort{ctrl: ctrl}
	mock.recorder = &MockUsersRepositoryInputPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUsersRepositoryInputPort) EXPECT() *MockUsersRepositoryInputPortMockRecorder {
	return m.recorder
}

// CreateUser mocks base method.
func (m *MockUsersRepositoryInputPort) CreateUser(ctx context.Context, user *entities.Users) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", ctx, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockUsersRepositoryInputPortMockRecorder) CreateUser(ctx, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockUsersRepositoryInputPort)(nil).CreateUser), ctx, user)
}

// GetAllUserIds mocks base method.
func (m *MockUsersRepositoryInputPort) GetAllUserIds(ctx context.Context) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllUserIds", ctx)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllUserIds indicates an expected call of GetAllUserIds.
func (mr *MockUsersRepositoryInputPortMockRecorder) GetAllUserIds(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllUserIds", reflect.TypeOf((*MockUsersRepositoryInputPort)(nil).GetAllUserIds), ctx)
}
